# Generated by Django 5.2.8 on 2026-02-14 03:50

from django.db import migrations, models


def add_valid_status_constraint_if_not_exists(apps, schema_editor):
    """Add valid_status check constraint only if it does not already exist."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1 FROM pg_constraint
                WHERE conname = 'valid_status'
                AND conrelid = 'django_blackbox_incident'::regclass
                """
            )
            if cursor.fetchone():
                return
    Incident = apps.get_model("django_blackbox", "Incident")
    constraint = models.CheckConstraint(
        check=models.Q(status__in=["OPEN", "ACKNOWLEDGED", "RESOLVED", "SUPPRESSED"]),
        name="valid_status",
    )
    schema_editor.add_constraint(Incident, constraint)


def remove_valid_status_constraint(apps, schema_editor):
    """Remove valid_status check constraint if it exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1 FROM pg_constraint
                WHERE conname = 'valid_status'
                AND conrelid = 'django_blackbox_incident'::regclass
                """
            )
            if not cursor.fetchone():
                return
    Incident = apps.get_model("django_blackbox", "Incident")
    constraint = models.CheckConstraint(
        check=models.Q(status__in=["OPEN", "ACKNOWLEDGED", "RESOLVED", "SUPPRESSED"]),
        name="valid_status",
    )
    schema_editor.remove_constraint(Incident, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ("django_blackbox", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_valid_status_constraint_if_not_exists, remove_valid_status_constraint),
    ]
